version: "3.9"
services:
  db:
    platform: "linux/arm64"
    image: mysql
    restart: always
    environment:
      HOST: 192.168.0.15
      MYSQL_DATABASE: "snippetbox"
      MYSQL_ROOT_PASSWORD: "Jdilla2006"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - snippetbox

  app:
    platform: "linux/arm64"
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    ports:
      - "4000:4000"
    expose:
      - "4000"
    volumes:
      - ./:/app/
    depends_on:
      - db
    networks:
      - snippetbox

networks:
  snippetbox:
    driver: bridge

volumes:
  mysql-data:
