version: "3.9"
services:
  nginx:
    platform: ${PLATFORM}
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: always
    environment:
        HOST: ${HOST}
        TZ: America/Buenos_Aires
    ports:
      - "80:80"
      - "443:443"
    networks:
      main:
        aliases:
          - nginx

  db:
    platform: ${PLATFORM}
    container_name: mysql
    image: mysql
    restart: always
    environment:
      HOST: ${HOST}
      MYSQL_DATABASE: "snippetbox"
      MYSQL_ROOT_PASSWORD: "xxxxx"
      TZ: America/Buenos_Aires
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      main:
        aliases:
          - mysql-db

  app:
    platform: ${PLATFORM}
    container_name: snippetbox
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    restart: always
    environment:
      HOST: ${HOST}
      TZ: America/Buenos_Aires
    ports:
      - "4000:4000"
    volumes:
      - ./:/app/
    depends_on:
      - db
    networks:
      main:
        aliases:
          - app
networks:
  main:

volumes:
  mysql-data:
