version: "3.9"
services:
  nginx:
    platform: "linux/arm64"
    container_name: nginx
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"

  db:
    platform: "linux/arm64"
    image: mysql
    restart: always
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    environment:
      HOST: 192.168.1.177
      MYSQL_DATABASE: "snippetbox"
      MYSQL_ROOT_PASSWORD: "Jdilla2006"
      TZ: America/Buenos_Aires
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - snippetbox

  app:
    platform: "linux/arm64"
    build:
      dockerfile: docker/app/Dockerfile
      context: .
    restart: always
    environment:
      HOST: 192.168.1.177
      TZ: America/Buenos_Aires
    ports:
      - "4000:4000"
    expose:
      - "4000"
    volumes:
      - ./:/app/
    depends_on:
      - db
    networks:
      - snippetbox

networks:
  snippetbox:
    driver: bridge

volumes:
  mysql-data:
